### PR TITLE
crypto scam search

### PR DESCRIPTION
**Pull request by Bektur1305**
This is a python code with the report inside. It contains histogram and pie-chart. It would be better to see in Jupyter notebook.

### CODE REVIEW

**Comment by christina-tkach** [comment]
@Bektur1305 thank you for submitting your report! Please, pay attention to the challenge description. All reports should be submitted as .md files with the following naming convention -  Name-of-the-crypto-project.md . If you are open to revising your submission, please make sure to follow the guidelines from the description of the challenge.

**Comment by Bektur1305** [comment]
@christina-tkach Added the report.

**Comment by christina-tkach** [comment]
@Bektur1305 please read the description of the challenge and the required report structure carefully. Unfortunately, we can't accept your current solution until it meets the requirements.

**Comment by Bektur1305** [comment]
@christina-tkach Added new report

**Review by christina-tkach — APPROVED** [review]

**Comment by christina-tkach** [comment]
@Bektur1305 hey, thanks for participating in the challenge! I contacted you via email

**Pull request merged**
